export type Status='Planned'|'In progress'|'Live demo'
export type ProjectTheme='api'|'realtime'|'ai'|'kit'
export type StackGroup={label:'Backend'|'Data'|'Infra'|'AI';items:string[]}
export type ProjectDetail={theme:ProjectTheme;bullets:string[];stack:StackGroup[];decisions:string[]}

export const samples:(ProjectDetail & {name:string;problem:string;does:string[];tech:string[];status:Status;note?:string;github:string;demo:string})[]=[
{name:'ClinicQueue',theme:'api',problem:'A small clinic chain needs bookings and reminders that do not double-book.',does:['Appointment booking API','SMS/email reminders','Admin, doctor and patient roles'],tech:['Spring Boot','PostgreSQL','Redis','SES/SNS'],status:'Planned',github:'',demo:'',bullets:['Appointment booking API','SMS/email reminders','Admin, doctor and patient roles'],stack:[{label:'Backend',items:['Spring Boot']},{label:'Data',items:['PostgreSQL','Redis']},{label:'Infra',items:['SES/SNS']},{label:'AI',items:[]}],decisions:['Design intent: keep booking and reminder behavior behind the Spring Boot API.','Design intent: use PostgreSQL for the relational booking data.','Design intent: use Redis where shared fast-access state is useful.']},
{name:'ColdChain Pulse',theme:'realtime',problem:'A food-delivery startup needs to know when a cold box warms up.',does:['Ingests temperature and humidity readings','Threshold alerts','AI summary of anomalies'],tech:['MQTT','Spring Boot','PostgreSQL','React','Spring AI'],status:'Planned',note:'Uses simulated devices',github:'',demo:'',bullets:['Ingests temperature and humidity readings','Threshold alerts','AI summary of anomalies'],stack:[{label:'Backend',items:['Spring Boot']},{label:'Data',items:['PostgreSQL']},{label:'Infra',items:['MQTT','React']},{label:'AI',items:['Spring AI']}],decisions:['Design intent: MQTT carries device readings into the backend path.','Design intent: PostgreSQL stores the readings used by the dashboard and alert flow.','Design intent: Spring AI is used for anomaly summaries rather than open-ended chat.']},
{name:'FounderDocs',theme:'ai',problem:'A team wants answers from internal docs without leaking restricted ones.',does:['Document ingestion and embeddings','Q&A grounded in retrieved text','Retrieval limited by user role'],tech:['Spring AI','pgvector','JWT/RBAC'],status:'Planned',github:'',demo:'',bullets:['Document ingestion and embeddings','Q&A grounded in retrieved text','Retrieval limited by user role'],stack:[{label:'Backend',items:['Spring AI','JWT/RBAC']},{label:'Data',items:['pgvector']},{label:'Infra',items:[]},{label:'AI',items:['Embeddings','RAG']}],decisions:['Design intent: retrieval is constrained by the requesting user role.','Design intent: pgvector holds the vector-search layer for document retrieval.','Design intent: answers stay grounded in retrieved internal text.']},
{name:'Feature drop kit',theme:'kit',problem:'An existing SaaS or shop backend needs common add-ons without a rewrite.',does:['Coupon engine','Low-stock alerts over Kafka','Webhook receiver with retries'],tech:['Spring Boot','Kafka','Redis'],status:'Planned',github:'',demo:'',bullets:['Coupon engine','Low-stock alerts over Kafka','Webhook receiver with retries'],stack:[{label:'Backend',items:['Spring Boot']},{label:'Data',items:['Redis']},{label:'Infra',items:['Kafka']},{label:'AI',items:[]}],decisions:['Design intent: add the modules around an existing backend instead of replacing it.','Design intent: Kafka carries the low-stock event path.','Design intent: Redis supports fast-access state where the module needs it.']},
]
export const built:(ProjectDetail & {name:string;when:string;tech:string;bullets:string[];github?:string;demo?:string})[]=[
{name:'Digital Library Platform',theme:'api',when:'2025 – Present',tech:'Spring Boot 3, Java 21, React.js, PostgreSQL, Redis, Docker, AWS',bullets:['REST APIs, Spring Data JPA, Flyway migrations, role-based workflows for readers, vendors and admins.','JWT authentication, Redis caching, S3 storage for book files, SES/SNS notifications.','Docker Compose on AWS EC2 with GitHub Actions CI/CD.'],stack:[{label:'Backend',items:['Spring Boot 3','Java 21','Spring Data JPA','JWT']},{label:'Data',items:['PostgreSQL','Redis','Flyway']},{label:'Infra',items:['Docker','AWS EC2','S3','SES/SNS','GitHub Actions']},{label:'AI',items:[]}],decisions:['Design intent: role-based workflows separate reader, vendor and admin access.','Design intent: Redis is part of the caching layer for frequently accessed data.','Design intent: S3 handles book-file storage while the application remains API-driven.'],github:'',demo:''},
{name:'PolicyDocs RAG Service',theme:'ai',when:'2025 – Present',tech:'Spring Boot 3, Spring AI, Java 21, PostgreSQL + pgvector, Redis, Docker, AWS',bullets:['Document ingestion, chunking, embeddings and RAG-based Q&A over policy documents.','pgvector retrieval, conversation context, structured outputs; JWT and RBAC constrain retrieval.','Docker on AWS EC2; grounded responses, no open LLM access.'],stack:[{label:'Backend',items:['Spring Boot 3','Java 21','JWT','RBAC']},{label:'Data',items:['PostgreSQL','pgvector','Redis']},{label:'Infra',items:['Docker','AWS EC2']},{label:'AI',items:['Spring AI','Embeddings','RAG','Structured Outputs']}],decisions:['Design intent: pgvector handles semantic retrieval over policy-document chunks.','Design intent: JWT and RBAC constrain which retrieved context can be used.','Design intent: the LLM API is called by the RAG pipeline rather than exposed as open chat.'],github:'',demo:''},
]