import {Canvas,useFrame,useThree} from '@react-three/fiber'
import {Line} from '@react-three/drei'
import {EffectComposer,Bloom} from '@react-three/postprocessing'
import {useEffect,useMemo,useRef,useState} from 'react'
import * as THREE from 'three'

const reduce=typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion: reduce)').matches
const mobile=typeof matchMedia!=='undefined'&&matchMedia('(hover: none)').matches
const traceDefs=[[[ -1.2,.08,-.7],[-.4,.1,-.7],[.2,.12,-.25]],[[ -1.1,.08,.55],[-.45,.1,.55],[.45,.12,.25],[1.2,.14,.55]],[[ .1,.1,-.75],[.55,.12,-.2],[1.1,.16,-.1]],[[ -.15,.11,.7],[.35,.14,.8],[1.1,.16,.45]]]
function curveFor(def:number[][]){return new THREE.CatmullRomCurve3(def.map(p=>new THREE.Vector3(p[0],p[1],p[2])))}
function Trace({curve,progress}:{curve:THREE.CatmullRomCurve3;progress:number}){const ref=useRef<THREE.TubeGeometry>(null);useEffect(()=>{if(ref.current){const count=ref.current.index?.count??0;ref.current.setDrawRange(0,Math.floor(count*progress))}},[progress]);return <mesh><tubeGeometry ref={ref} args={[curve,48,.018,6,false]}/><meshStandardMaterial color={tokens.copper} emissive={tokens.copper} emissiveIntensity={.15}/></mesh>}
function Packet({curve,delay}:{curve:THREE.CatmullRomCurve3;delay:number}){const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(!ref.current||reduce)return;const t=Math.min(1,Math.max(0,(clock.elapsedTime-delay)/1.1));const e=t*t*(3-2*t);ref.current.position.copy(curve.getPointAt(e));ref.current.scale.setScalar(t>0&&t<1?1:0)});return <mesh ref={ref}><sphereGeometry args={[.045,8,8]}/><meshBasicMaterial color={tokens.signal}/></mesh>}
function Board(){const group=useRef<THREE.Group>(null);const tokens=useMemo(()=>{const s=getComputedStyle(document.documentElement);return {solder:s.getPropertyValue('--solder').trim(),deep:s.getPropertyValue('--deep').trim(),copper:s.getPropertyValue('--copper').trim(),signal:s.getPropertyValue('--signal').trim(),ink:s.getPropertyValue('--ink').trim()}},[]);const [phase,setPhase]=useState(reduce?1:0);const curves=useMemo(()=>traceDefs.map(curveFor),[]);const nodes=useMemo(()=>Array.from({length:mobile?12:24},(_,i)=>new THREE.Vector3(Math.sin(i*7.1)*2.1,1.05+(i%6)*.28,Math.cos(i*4.7)*1.3)),[]);useEffect(()=>{if(reduce){setPhase(1);return}const timers=[setTimeout(()=>setPhase(.2),300),setTimeout(()=>setPhase(.45),900),setTimeout(()=>setPhase(.7),1500),setTimeout(()=>setPhase(1),2400)];return()=>timers.forEach(clearTimeout)},[]);useFrame((_,dt)=>{if(group.current&&!reduce){group.current.rotation.y+=dt*.05;group.current.position.y=Math.sin(performance.now()*.00035)*.015}});return <group ref={group} rotation={[.28,.2,0]}><mesh><boxGeometry args={[3,.12,2]}/><meshStandardMaterial color={tokens.solder}/></mesh><mesh position={[.35,.13,0]}><boxGeometry args={[.7,.14,.65]}/><meshStandardMaterial color={tokens.deep}/></mesh><mesh position={[1.15,.22,.62]}><sphereGeometry args={[.07,12,12]}/><meshBasicMaterial color="var(--signal)"/></mesh>{curves.map((c,i)=><Trace key={i} curve={c} progress={Math.max(0,Math.min(1,(phase-.2-i*.06)/.55))}/>)}{curves.slice(0,3).map((c,i)=><Packet key={'p'+i} curve={c} delay={1.4+i*.18}/>) }{nodes.map((n,i)=><mesh key={i} position={n}><sphereGeometry args={[.035,6,6]}/><meshBasicMaterial color={tokens.ink}/></mesh>)}{nodes.slice(0,10).map((n,i)=><line key={'l'+i}><bufferGeometry><bufferAttribute attach="attributes-position" args={[new Float32Array([.8,.2,.4,n.x,n.y,n.z]),3]}/></bufferGeometry><lineBasicMaterial color="var(--ink)" transparent opacity={phase*.22}/></line>)}</group>}
function Scene(){const {camera}=useThree();useEffect(()=>{const onScroll=()=>{const y=window.scrollY;camera.position.x=THREE.MathUtils.clamp(y/window.innerHeight*.12,-.2,.2);camera.position.y=1.5+THREE.MathUtils.clamp(y/window.innerHeight*.4,-.4,.4)};window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[camera]);return <><ambientLight intensity={1.1}/><directionalLight position={[3,5,2]} intensity={1.2}/><Board/>{!mobile&&!reduce&&<EffectComposer><Bloom intensity={.35} luminanceThreshold={.75} mipmapBlur/></EffectComposer>}</>}
export default function BoardScene(){return <Canvas dpr={[1,1.5]} camera={{position:[0,1.5,6],fov:40}} frameloop="always" onPointerDown={()=>{}}><Scene/></Canvas>}
